architecture: ArchitectureNew

ArchitectureNew:
  prompter_patch_size: 20
  backbone_wanted: ResNet50
  backbone_supervised: ResNet101
  rpn_head_wanted: RPNHead
  rpn_head_supervised: RPNHead
  bbox_head_wanted: BBoxHead
  bbox_head_supervised: BBoxHead
  bbox_post_process_wanted: BBoxPostProcess
  bbox_post_process_supervised: BBoxPostProcess
  weights_wanted_url: https://paddledet.bj.bcebos.com/models/faster_rcnn_r50_1x_coco.pdparams
  weights_supervised_url: https://paddledet.bj.bcebos.com/models/faster_rcnn_r101_1x_coco.pdparams

ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [2]
  num_stages: 3

RPNHead:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    anchor_sizes: [32, 64, 128, 256, 512]
    strides: [16]
  rpn_target_assign:
    batch_size_per_im: 256
    fg_fraction: 0.5
    negative_overlap: 0.3
    positive_overlap: 0.7
    use_random: True
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 12000
    post_nms_top_n: 2000
    topk_after_collect: False
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 6000
    post_nms_top_n: 1000

BBoxHead:
  head: Res5Head
  roi_extractor:
    resolution: 14
    sampling_ratio: 0
    aligned: True
  bbox_assigner: BBoxAssigner
  with_pool: true

BBoxAssigner:
  batch_size_per_im: 512
  bg_thresh: 0.5
  fg_thresh: 0.5
  fg_fraction: 0.25
  use_random: True

BBoxPostProcess:
  decode: RCNNBox
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.05
    nms_threshold: 0.5

_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/faster_reader.yml',
]

pretrain_weights: output/customed/model.pdparams
weights: output/customed/model.pdparams
